import type { Metadata } from "next";

import 'primereact/resources/themes/lara-dark-teal/theme.css'

export const metadata: Metadata = {
    title: "Trader",
    description: "Generated by create next app",
};

export default function TraderLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section className="w-screen h-screen">
            {children}
        </section>
    ); 
}